# 公共配置文件
spring:
  application:
    name: lilyOj-service-client
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  sentinel:
    datasource: nacos
server:
  servlet:
      context-path: /api/client
# 接口文档配置
knife4j:
  enable: true